name: Nuget - Build and Publish

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Restore dependencies
      working-directory: src/ParallelTCP
      run: dotnet restore
      
    - name: Build
      working-directory: src/ParallelTCP
      run: dotnet build --no-restore -c Release
      
    - name: Packaging
      working-directory: src/ParallelTCP
      run: dotnet pack -c Release
      
    - name: Publish
      working-directory: src/ParallelTCP/bin
      run: dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/sharp0802/index.json" --api-key ${{secrets.NUGET_API_KEY}}
